/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "api-keys": () => import("@/views/api-keys/index.vue"),
  audit: () => import("@/views/audit/index.vue"),
  documents: () => import("@/views/documents/index.vue"),
  home: () => import("@/views/home/index.vue"),
  import: () => import("@/views/import/index.vue"),
  jobs: () => import("@/views/jobs/index.vue"),
  libraries: () => import("@/views/libraries/index.vue"),
  permissions: () => import("@/views/permissions/index.vue"),
  search: () => import("@/views/search/index.vue"),
  users: () => import("@/views/users/index.vue"),
};
