/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'api-keys',
    path: '/api-keys',
    component: 'layout.base$view.api-keys',
    meta: {
      title: '我的 API Key',
      icon: 'mdi:key-variant',
      order: 13
    }
  },
  {
    name: 'audit',
    path: '/audit',
    component: 'layout.base$view.audit',
    meta: {
      title: '审计日志',
      icon: 'mdi:history',
      order: 24,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'documents',
    path: '/documents',
    component: 'layout.base$view.documents',
    meta: {
      title: '文档',
      icon: 'mdi:file-document-outline',
      order: 10
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: '概览',
      icon: 'mdi:view-dashboard-outline',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      hideInMenu: true
    }
  },
  {
    name: 'import',
    path: '/import',
    component: 'layout.base$view.import',
    meta: {
      title: '导入数据',
      icon: 'mdi:database-import-outline',
      order: 12
    }
  },
  {
    name: 'jobs',
    path: '/jobs',
    component: 'layout.base$view.jobs',
    meta: {
      title: '任务监控',
      icon: 'mdi:cog-sync-outline',
      order: 23,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'libraries',
    path: '/libraries',
    component: 'layout.base$view.libraries',
    meta: {
      title: '库管理',
      icon: 'mdi:bookshelf',
      order: 21,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'permissions',
    path: '/permissions',
    component: 'layout.base$view.permissions',
    meta: {
      title: '权限矩阵',
      icon: 'mdi:shield-key-outline',
      order: 22,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'search',
    path: '/search',
    component: 'layout.base$view.search',
    meta: {
      title: '数据检索',
      icon: 'mdi:text-search',
      order: 11
    }
  },
  {
    name: 'users',
    path: '/users',
    component: 'layout.base$view.users',
    meta: {
      title: '用户管理',
      icon: 'mdi:account-group-outline',
      order: 20,
      roles: ['R_SUPER']
    }
  }
];
